import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame1(),
        ]),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 11,
                top: 55,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Página Inicial - Aluno',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 30,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 110,
                child: SizedBox(
                  width: 341,
                  height: 23,
                  child: Text(
                    'Nome do estudante',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 107,
                child: Container(
                  width: 27,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 146,
                child: Container(
                  width: 430,
                  height: 788,
                  decoration: BoxDecoration(color: const Color(0xFFF1EFEF)),
                ),
              ),
              Positioned(
                left: 16,
                top: 157,
                child: Container(
                  width: 391,
                  height: 41,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4E6FFC),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 109,
                child: Container(
                  width: 23,
                  height: 22,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 27,
                top: 167,
                child: SizedBox(
                  width: 329,
                  height: 21,
                  child: Text(
                    'Quadro de Horários',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 222,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Matérias',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 27,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 271,
                child: Container(
                  width: 396,
                  height: 87,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFAFA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 497,
                child: Container(
                  width: 396,
                  height: 87,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFAFA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 610,
                child: Container(
                  width: 396,
                  height: 87,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFAFA),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 381.52,
                top: 191.96,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 27.49,
                  height: 27.49,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 874,
                child: Container(
                  width: 430,
                  height: 58,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 162,
                top: 830,
                child: Container(
                  width: 91,
                  height: 87,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4E6FFC),
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 2,
                        color: const Color(0xFF133EF5),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 184,
                top: 850,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 80,
                top: 293,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Cálculo 1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 293,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Cálculo 1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 406,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Física 1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 519,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Geometria Analítica',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 632,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Algorítmos',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 741,
                child: SizedBox(
                  width: 360,
                  child: Text(
                    'Álgebra Linear',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 23,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 321,
                child: SizedBox(
                  width: 91,
                  height: 19,
                  child: Text(
                    'Professor: X',
                    style: TextStyle(
                      color: const Color(0xFF4C4C4C),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 434,
                child: SizedBox(
                  width: 91,
                  height: 19,
                  child: Text(
                    'Professor: X',
                    style: TextStyle(
                      color: const Color(0xFF4C4C4C),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 319,
                top: 878,
                child: Container(
                  width: 39,
                  height: 39,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 80,
                top: 547,
                child: SizedBox(
                  width: 91,
                  height: 19,
                  child: Text(
                    'Professor: X',
                    style: TextStyle(
                      color: const Color(0xFF4C4C4C),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 629,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 80,
                top: 660,
                child: SizedBox(
                  width: 91,
                  height: 19,
                  child: Text(
                    'Professor: X',
                    style: TextStyle(
                      color: const Color(0xFF4C4C4C),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 769,
                child: SizedBox(
                  width: 91,
                  height: 19,
                  child: Text(
                    'Professor: X',
                    style: TextStyle(
                      color: const Color(0xFF4C4C4C),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 740,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 356.53,
                top: 337.05,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 42.52,
                  height: 42.52,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 354.53,
                top: 449.05,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 42.52,
                  height: 42.52,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 356.53,
                top: 562.05,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 42.52,
                  height: 42.52,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 356.53,
                top: 676.05,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 42.52,
                  height: 42.52,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 355.53,
                top: 788.05,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.58),
                  width: 42.52,
                  height: 42.52,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 24,
                top: 292,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 24,
                top: 407,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 24,
                top: 518,
                child: Container(
                  width: 48,
                  height: 48,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 60,
                top: 881,
                child: Container(
                  width: 36,
                  height: 36,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
